// <auto-generated />
using System;
using System.Collections.Generic;
using System.Net;
using Core.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Core.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251119153945_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Features.Auth.DeviceInformations.DeviceInformation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientName")
                        .HasColumnType("text");

                    b.Property<string>("ClientType")
                        .HasColumnType("text");

                    b.Property<string>("ClientVersion")
                        .HasColumnType("text");

                    b.Property<string>("DeviceBrand")
                        .HasColumnType("text");

                    b.Property<string>("DeviceModel")
                        .HasColumnType("text");

                    b.Property<string>("DeviceName")
                        .HasColumnType("text");

                    b.Property<string>("FcmToken")
                        .HasColumnType("text");

                    b.Property<string>("OsName")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("DeviceInformation");
                });

            modelBuilder.Entity("Core.Features.Auth.LoginActivities.LoginActivity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DeviceInfoId")
                        .HasColumnType("bigint");

                    b.Property<IPAddress>("IPAddress")
                        .IsRequired()
                        .HasColumnType("inet");

                    b.Property<DateTimeOffset>("LoginTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LogoutTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DeviceInfoId");

                    b.HasIndex("UserId");

                    b.ToTable("LoginActivities");
                });

            modelBuilder.Entity("Core.Features.Auth.OtpVerifications.OtpVerification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Otp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.ComplexProperty<Dictionary<string, object>>("CreationTime", "Core.Features.Auth.OtpVerifications.OtpVerification.CreationTime#CreationTime", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("CreatedAt");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("DeletionInfo", "Core.Features.Auth.OtpVerifications.OtpVerification.DeletionInfo#DeletionInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("DeletedAt");

                            b1.Property<long?>("DeletedBy")
                                .HasColumnType("bigint")
                                .HasColumnName("DeletedBy");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean")
                                .HasColumnName("IsDeleted");
                        });

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("OtpVerifications");
                });

            modelBuilder.Entity("Core.Features.Auth.RefreshTokens.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<IPAddress>("IPAddress")
                        .IsRequired()
                        .HasColumnType("inet");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.ComplexProperty<Dictionary<string, object>>("CreationTime", "Core.Features.Auth.RefreshTokens.RefreshToken.CreationTime#CreationTime", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("CreatedAt");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Core.Features.PermissionManagement.Permissions.Permission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsSystemManaged")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty<Dictionary<string, object>>("DeletionInfo", "Core.Features.PermissionManagement.Permissions.Permission.DeletionInfo#DeletionInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("DeletedAt");

                            b1.Property<long?>("DeletedBy")
                                .HasColumnType("bigint")
                                .HasColumnName("DeletedBy");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean")
                                .HasColumnName("IsDeleted");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Core.Features.PermissionManagement.RolePermissions.RolePermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("PermissionId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.ComplexProperty<Dictionary<string, object>>("DeletionInfo", "Core.Features.PermissionManagement.RolePermissions.RolePermission.DeletionInfo#DeletionInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("DeletedAt");

                            b1.Property<long?>("DeletedBy")
                                .HasColumnType("bigint")
                                .HasColumnName("DeletedBy");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean")
                                .HasColumnName("IsDeleted");
                        });

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("Core.Features.PermissionManagement.Roles.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsSystemManaged")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("User");

                    b.ComplexProperty<Dictionary<string, object>>("DeletionInfo", "Core.Features.PermissionManagement.Roles.Role.DeletionInfo#DeletionInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("DeletedAt");

                            b1.Property<long?>("DeletedBy")
                                .HasColumnType("bigint")
                                .HasColumnName("DeletedBy");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean")
                                .HasColumnName("IsDeleted");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("UpdateInfo", "Core.Features.PermissionManagement.Roles.Role.UpdateInfo#UpdateInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("UpdatedAt");

                            b1.Property<long?>("UpdatedBy")
                                .HasColumnType("bigint")
                                .HasColumnName("UpdatedBy");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Core.Features.PermissionManagement.UserRoles.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.ComplexProperty<Dictionary<string, object>>("DeletionInfo", "Core.Features.PermissionManagement.UserRoles.UserRole.DeletionInfo#DeletionInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("DeletedAt");

                            b1.Property<long?>("DeletedBy")
                                .HasColumnType("bigint")
                                .HasColumnName("DeletedBy");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean")
                                .HasColumnName("IsDeleted");
                        });

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Core.Features.Rentals.Entity.Movie", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<int>("RentalType")
                        .HasColumnType("integer");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty<Dictionary<string, object>>("DeletionInfo", "Core.Features.Rentals.Entity.Movie.DeletionInfo#DeletionInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("DeletedAt");

                            b1.Property<long?>("DeletedBy")
                                .HasColumnType("bigint")
                                .HasColumnName("DeletedBy");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean")
                                .HasColumnName("IsDeleted");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("UpdateInfo", "Core.Features.Rentals.Entity.Movie.UpdateInfo#UpdateInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<long?>("UpdatedBy")
                                .HasColumnType("bigint");
                        });

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Core.Features.Rentals.Entity.RentalE", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("numeric");

                    b.Property<int>("userid")
                        .HasColumnType("integer");

                    b.ComplexProperty<Dictionary<string, object>>("CreationInfo", "Core.Features.Rentals.Entity.RentalE.CreationInfo#CreationInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("CreatedBy")
                                .HasColumnType("bigint");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("DeletionInfo", "Core.Features.Rentals.Entity.RentalE.DeletionInfo#DeletionInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("DeletedAt");

                            b1.Property<long?>("DeletedBy")
                                .HasColumnType("bigint")
                                .HasColumnName("DeletedBy");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean")
                                .HasColumnName("IsDeleted");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("UpdateInfo", "Core.Features.Rentals.Entity.RentalE.UpdateInfo#UpdateInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<long?>("UpdatedBy")
                                .HasColumnType("bigint");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("Core.Features.Rentals.Entity.RentalItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<long>("MovieId1")
                        .HasColumnType("bigint");

                    b.Property<int>("RentalId")
                        .HasColumnType("integer");

                    b.Property<long>("RentalId1")
                        .HasColumnType("bigint");

                    b.ComplexProperty<Dictionary<string, object>>("CreationInfo", "Core.Features.Rentals.Entity.RentalItem.CreationInfo#CreationInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("CreatedBy")
                                .HasColumnType("bigint");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("UpdateInfo", "Core.Features.Rentals.Entity.RentalItem.UpdateInfo#UpdateInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<long?>("UpdatedBy")
                                .HasColumnType("bigint");
                        });

                    b.HasKey("Id");

                    b.HasIndex("MovieId1");

                    b.HasIndex("RentalId1");

                    b.ToTable("RentalItems");
                });

            modelBuilder.Entity("Core.Features.Users.Entity.AchievementTier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("MaxPoints")
                        .HasColumnType("integer");

                    b.Property<int>("MinPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.ComplexProperty<Dictionary<string, object>>("CreationInfo", "Core.Features.Users.Entity.AchievementTier.CreationInfo#CreationInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("CreatedAt");

                            b1.Property<long>("CreatedBy")
                                .HasColumnType("bigint")
                                .HasColumnName("CreatedBy");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("DeletionInfo", "Core.Features.Users.Entity.AchievementTier.DeletionInfo#DeletionInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("DeletedAt");

                            b1.Property<long?>("DeletedBy")
                                .HasColumnType("bigint")
                                .HasColumnName("DeletedBy");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean")
                                .HasColumnName("IsDeleted");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_AchievementTier_Name");

                    b.HasIndex("MinPoints", "MaxPoints")
                        .HasDatabaseName("IX_AchievementTier_MinMaxPoints");

                    b.ToTable("AchievementTier");
                });

            modelBuilder.Entity("Core.Features.Users.Entity.DashboardFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("FileType")
                        .HasColumnType("integer");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.ComplexProperty<Dictionary<string, object>>("CreationInfo", "Core.Features.Users.Entity.DashboardFile.CreationInfo#CreationInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("CreatedAt");

                            b1.Property<long>("CreatedBy")
                                .HasColumnType("bigint")
                                .HasColumnName("CreatedBy");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("DeletionInfo", "Core.Features.Users.Entity.DashboardFile.DeletionInfo#DeletionInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("DeletedAt");

                            b1.Property<long?>("DeletedBy")
                                .HasColumnType("bigint")
                                .HasColumnName("DeletedBy");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean")
                                .HasColumnName("IsDeleted");
                        });

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DashboardFiles");
                });

            modelBuilder.Entity("Core.Features.Users.Entity.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserProfileImageUrl")
                        .HasColumnType("text");

                    b.ComplexProperty<Dictionary<string, object>>("ContactInfo", "Core.Features.Users.Entity.User.ContactInfo#UserContactInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("PhoneNumber")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("PhoneNumber");

                            b1.Property<bool>("PhoneNumberConfirmed")
                                .HasColumnType("boolean")
                                .HasColumnName("PhoneNumberConfirmed");

                            b1.Property<string>("RegionCode")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("RegionCode");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("DeletionInfo", "Core.Features.Users.Entity.User.DeletionInfo#DeletionInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("DeletedAt");

                            b1.Property<long?>("DeletedBy")
                                .HasColumnType("bigint")
                                .HasColumnName("DeletedBy");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean")
                                .HasColumnName("IsDeleted");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Email", "Core.Features.Users.Entity.User.Email#UserEmail", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Email");

                            b1.Property<bool>("EmailConfirmed")
                                .HasColumnType("boolean")
                                .HasColumnName("EmailConfirmed");

                            b1.Property<string>("EmailNormalized")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("EmailNormalized");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Password", "Core.Features.Users.Entity.User.Password#UserPassword", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("PasswordHash")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("Password");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PersonalName", "Core.Features.Users.Entity.User.PersonalName#UserPersonalName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("LastName");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Username", "Core.Features.Users.Entity.User.Username#UserUsername", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Username");

                            b1.Property<string>("UsernameNormalized")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("UsernameNormalized");
                        });

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Core.Features.Users.Entity.UserAchievement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AchievementTierId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("DateEarned")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("PointsEarned")
                        .HasColumnType("double precision");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.ComplexProperty<Dictionary<string, object>>("CreationInfo", "Core.Features.Users.Entity.UserAchievement.CreationInfo#CreationInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("CreatedAt");

                            b1.Property<long>("CreatedBy")
                                .HasColumnType("bigint")
                                .HasColumnName("CreatedBy");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("DeletionInfo", "Core.Features.Users.Entity.UserAchievement.DeletionInfo#DeletionInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("DeletedAt");

                            b1.Property<long?>("DeletedBy")
                                .HasColumnType("bigint")
                                .HasColumnName("DeletedBy");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean")
                                .HasColumnName("IsDeleted");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AchievementTierId");

                    b.HasIndex("PointsEarned")
                        .HasDatabaseName("IX_UserAchievement_PointsEarned");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserAchievement_UserId");

                    b.ToTable("UserAchievement");
                });

            modelBuilder.Entity("Core.Features.Auth.LoginActivities.LoginActivity", b =>
                {
                    b.HasOne("Core.Features.Auth.DeviceInformations.DeviceInformation", "DeviceInfo")
                        .WithMany("LoginActivities")
                        .HasForeignKey("DeviceInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Features.Users.Entity.User", "User")
                        .WithMany("LoginActivities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeviceInfo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Features.Auth.OtpVerifications.OtpVerification", b =>
                {
                    b.HasOne("Core.Features.Users.Entity.User", "User")
                        .WithMany("Verifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Features.Auth.RefreshTokens.RefreshToken", b =>
                {
                    b.HasOne("Core.Features.Users.Entity.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Features.PermissionManagement.RolePermissions.RolePermission", b =>
                {
                    b.HasOne("Core.Features.PermissionManagement.Permissions.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Features.PermissionManagement.Roles.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Core.Features.PermissionManagement.UserRoles.UserRole", b =>
                {
                    b.HasOne("Core.Features.PermissionManagement.Roles.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Features.Users.Entity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Features.Rentals.Entity.RentalE", b =>
                {
                    b.HasOne("Core.Features.Users.Entity.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Core.Features.Rentals.Entity.RentalItem", b =>
                {
                    b.HasOne("Core.Features.Rentals.Entity.Movie", "Movie")
                        .WithMany("RentalItems")
                        .HasForeignKey("MovieId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Features.Rentals.Entity.RentalE", "Rental")
                        .WithMany("RentalItems")
                        .HasForeignKey("RentalId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Rental");
                });

            modelBuilder.Entity("Core.Features.Users.Entity.DashboardFile", b =>
                {
                    b.HasOne("Core.Features.Users.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Features.Users.Entity.UserAchievement", b =>
                {
                    b.HasOne("Core.Features.Users.Entity.AchievementTier", "AchievementTier")
                        .WithMany()
                        .HasForeignKey("AchievementTierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Features.Users.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AchievementTier");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Features.Auth.DeviceInformations.DeviceInformation", b =>
                {
                    b.Navigation("LoginActivities");
                });

            modelBuilder.Entity("Core.Features.PermissionManagement.Permissions.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Core.Features.PermissionManagement.Roles.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Core.Features.Rentals.Entity.Movie", b =>
                {
                    b.Navigation("RentalItems");
                });

            modelBuilder.Entity("Core.Features.Rentals.Entity.RentalE", b =>
                {
                    b.Navigation("RentalItems");
                });

            modelBuilder.Entity("Core.Features.Users.Entity.User", b =>
                {
                    b.Navigation("LoginActivities");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");

                    b.Navigation("Verifications");
                });
#pragma warning restore 612, 618
        }
    }
}
